automationName: UiAutomator2
platformName: Android
platformVersion: '5.1.1'
deviceName: "127.0.0.1:62001"
appPackage: "com.xxzb.fenwoo"
appActivity: "com.xxzb.fenwoo.activity.addition.WelcomeActivity"
unicodeKeyboard: True
resetKeyboard: True
noReset: false
